#%RAML 1.0
version: v1.0
title: product

/product:
  get:
    responses: 
      200:
        body: 
          application/json:
            example:
             {
               "name":"Air conditioner",
               "price":40000
             }